trainer:
  gpus: 1
  max_epochs: 64
  gradient_clip_val: 1.0

data:
  train_path: "data/equation_verification/40k_train.json"
  val_path: "data/equation_verification/40k_val_shallow.json"
  batch_size: 128

defaults:
 - model: tree_rnn
