trainer:
  gpus: 1
  max_epochs: 256
  gradient_clip_val: 1.0

data:
  train_path: "data/equation_verification/40k_train.json"
  val_path: "data/equation_verification/40k_val_shallow.json"
  batch_size: 64

defaults:
 - model: graph_cnn
