trainer:
  gpus: 1
  max_epochs: 256
  gradient_clip_val: 1.0

data:
  train_path: "../data/equation_verification/40k_1_to_2_val.json"
  val_path: "../data/equation_verification/40k_1_to_2_val.json"
  batch_size: 64

defaults:
 - model: tree_lstm
